name: Go CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: |
          CGO_ENABLED=0 GOOS=linux go run main.go &
          sleep 5
          go test -run ^TestApp$ ./tests
